database:
  type: "sqlite" # o "postgresql"
  postgresql:
    host: "localhost"
    port: 5432
    user: "usuari"
    password: "contrasenya"
    dbname: "genealogia"
    sslmode: "disable"
  sqlite:
    path: "./db/genealogia.db"